---
version: 2

# FastAPI Service Template Dependabot configuration (root repo template)

updates:
  - package-ecosystem: "pip"
    directory: "/skeleton"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 8
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels: ["dependencies", "python", "fastapi"]
    ignore:
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uvicorn"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:10"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: ["dependencies", "github-actions", "ci"]
