apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoUrl | projectSlug }}
  tags:
    - vue
    - frontend
    - typescript
    - vite
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
