name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r skeleton/requirements.txt

      - name: [33mLint with flake8 [0m🧹
        run: |
          pip install flake8
          flake8 skeleton/src/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: [32mRun tests [0m🧪
        run: |
          pip install pytest
          pytest skeleton/src/ || pytest skeleton/

      - name: [36mCheck formatting (black) [0m🎨
        run: |
          pip install black
          black --check skeleton/src/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: skeleton/src/.pytest_cache
