site_name: BACKSTAGE_ENTITY_NAME API Documentation
site_description: Comprehensive documentation for the BACKSTAGE_ENTITY_NAME ASP.NET Core Web API

repo_url: https://github.com/${{values.destination.owner}}/${{values.name}}
repo_name: ${{values.destination.owner}}/${{values.name}}

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Architecture: architecture.md
  - Testing: testing.md
  - Deployment: deployment.md
  - Contributing: contributing.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - admonition
#   - pymdownx.details
#   - attr_list
#   - md_in_html
#   - tables
#   - toc:
#       permalink: true

plugins:
  - search
  # - glightbox
