apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.owner}}/${{values.name}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - system
    - architecture
spec:
  owner: ${{values.owner}}
