---
version: 2

# MCP Server Node Template Dependabot configuration

updates:
  - package-ecosystem: "npm"
    directory: "/skeleton"
    schedule:
      interval: weekly
      day: monday
      time: "08:10"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "npm"
      include: "scope"
    labels: ["dependencies", "npm", "mcp"]
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:20"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: ["dependencies", "github-actions", "ci"]
