apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - gitops
    - kubernetes
    - ${{ values.environment }}
spec:
  owner: ${{ values.owner }}
