name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'
        
    - name: Lint Helm chart
      run: |
        helm lint .
        echo "✅ Helm chart syntax validation passed"

  template:
    name: Template and Validate
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'
        
    - name: Template Helm chart
      run: |
        helm template test-release . --values values.yaml > rendered-manifests.yaml
        echo "✅ Helm chart templating completed"
        
    - name: Validate Kubernetes manifests
      run: |
        # Install kubeval for Kubernetes manifest validation
        curl -L https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar xz
        sudo cp kubeval /usr/local/bin
        
        # Validate rendered manifests
        kubeval rendered-manifests.yaml
        echo "✅ Kubernetes manifest validation passed"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    needs: [lint, template]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'
        
    - name: Package Helm chart
      run: |
        helm package .
        echo "✅ Helm chart packaging completed"
        
    - name: Upload chart package
      uses: actions/upload-artifact@v4
      with:
        name: helm-chart
        path: '*.tgz'