apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.destination.owner}}/${{values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - fastapi
    - python
    - api
    - microservice
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system | default("platform")}}
  # providesApis:
  #   - ${{values.name}}-api
